#!/bin/bash
apt-get -y update
apt-get -y install curl

nonTwoHundo=0

COUNTER=0
while [  $COUNTER -lt 100 ]; do
  statusCode=$(curl -w '%{http_code}' -s -o /dev/null sample-error-app-happy-camel.apps.pcf-pre3.pal.pivotal.io)
  echo "$statusCode"
  if [ "$statusCode" != "200" ]; then
    nonTwoHundo=$(($nonTwoHundo + 1))
  fi
  COUNTER=$(($COUNTER + 1))
done
