#!/bin/bash
eval $(cat sli-value/value)
if [[  $nonTwoHundo -gt 10 ]]; then
  echo "PRE3: Too many 500s" | tee slo-failure/message
  exit 1
fi

echo "total 200s: $nonTwoHundo"
echo "PRE3: Finished" | tee slo-failure/message
exit 0
