---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ubuntu

inputs:
- name: team-source
- name: sli-value

outputs:
- name: slo-failure

run:
  path: team-source/ci/tasks/measure-sli
