#!/bin/bash
eval $(cat sli-value/value)
if [[  $nonTwoHundo -gt 1 ]]; then
  echo "total 200s: $nonTwoHundo"
  echo "PRE3: Too many 400s" | tee slo-failure/message
  exit 1
fi

echo "total 200s: $nonTwoHundo"
echo "PRE3: Finished" | tee slo-failure/message
exit 0
