#!/bin/bash
if [ "$statusCode" == "200" ]; then
  echo "Bad Status Code"
  exit 1
fi

echo "Finished"
exit 1
# Here, you will write your task. Make sure that the task exits with a return code of 0 if
# successful and 1 (or some other non-zero) value if it fails!
